# Generated by Django 3.2.4 on 2021-09-03 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='reveived',
            new_name='received',
        ),
    ]
